version: '3'
services:
  frontend:
    ports:
      - "4100:4100"
    build:
      context: frontend
      args:
        BACKEND_URL_ARG: backend
    depends_on:
      - backend

  backend:
    ports:
      - "8080:8080"
    build:
      context: backend
      args:
        DB_URL_ARG: mysql
        DB_PORT_ARG: 3306
        DB_NAME_ARG: db
        DB_USERNAME_ARG: db_user
        DB_PASSWORD_ARG: passwD
    depends_on:
      - mysql

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=passwD